# kind: pipeline
# type: docker
# name: amd64-mini

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: mini.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-mini", "${DRONE_COMMIT_BRANCH}-mini"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-mini"

# trigger:
#   event:
#     - push

# ---
# kind: pipeline
# type: docker
# name: arm64-mini

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: mini.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-mini-arm64", "${DRONE_COMMIT_BRANCH}-mini-arm64"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev_arm64"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-mini-arm64"

# trigger:
#   branch:
#     - dev
#   event:
#     - push

# ---
# kind: pipeline
# type: docker
# name: amd64-common

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: common.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-common", "${DRONE_COMMIT_BRANCH}-common"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-common"

# trigger:
#   event:
#     - push

# ---
# kind: pipeline
# type: docker
# name: arm64-common

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: common.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-common-arm64", "${DRONE_COMMIT_BRANCH}-common-arm64"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev_arm64"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-common-arm64"

# trigger:
#   branch:
#     - dev
#   event:
#     - push

# ---
# kind: pipeline
# type: docker
# name: amd64-exec-env

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: exec-env.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-exec-env", "${DRONE_COMMIT_BRANCH}-exec-env"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-exec-env"

# trigger:
#   event:
#     - push

# ---
# kind: pipeline
# type: docker
# name: arm64-exec-env

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: exec-env.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-exec-env-arm64", "${DRONE_COMMIT_BRANCH}-exec-env-arm64"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev_arm64"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-exec-env-arm64"

# trigger:
#   branch:
#     - dev
#   event:
#     - push

# ---
kind: pipeline
type: docker
name: amd64-torch-cpu

platform:
  arch: amd64

steps:
  - name: set base file
    image: alpine
    commands:
      - sed -i 's/CURRENT_BRANCH_NAME/${DRONE_COMMIT_BRANCH}/' torch-cpu.dev.Dockerfile
      - cat torch-cpu.dev.Dockerfile
      - echo ${DRONE_COMMIT_BRANCH}
  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: torch-cpu.dev.Dockerfile
      registry: registry.dev.onetask.ai
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: "registry.dev.onetask.ai/${DRONE_REPO}"
      tags: ["${DRONE_COMMIT_SHA}-torch-cpu", "${DRONE_COMMIT_BRANCH}-torch-cpu"]
      cache_from:
        - "registry.dev.onetask.ai/${DRONE_REPO}:dev"
        - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-torch-cpu"

# depends_on:
#   - amd64-common

trigger:
  event:
    - push

# ---
# kind: pipeline
# type: docker
# name: arm64-torch-cpu

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: torch-cpu.dev.Dockerfile
#       registry: registry.dev.onetask.ai
#       username:
#         from_secret: docker_username
#       password:
#         from_secret: docker_password
#       repo: "registry.dev.onetask.ai/${DRONE_REPO}"
#       tags: ["${DRONE_COMMIT_SHA}-torch-cpu-arm64", "${DRONE_COMMIT_BRANCH}-torch-cpu-arm64"]
#       cache_from:
#         - "registry.dev.onetask.ai/${DRONE_REPO}:dev_arm64"
#         - "registry.dev.onetask.ai/${DRONE_REPO}:${DRONE_COMMIT_BRANCH}-torch-cpu-arm64"

# depends_on:
#   - arm64-common

# trigger:
#   branch:
#     - dev
#   event:
#     - push

# ---
# kind: pipeline
# type: docker
# name: amd64-mini-dockerhub

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: mini.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-mini-drone-amd64"

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: arm64-mini-dockerhub

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: mini.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-mini-drone-arm64"

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# name: manifest-mini
# steps:
# - name: manifest
#   image: plugins/manifest
#   settings:
#     spec: manifests/mini-drone-manifest.tmpl
#     tag: "${DRONE_TAG}-mini"
#     ignore_missing: true
#     username:
#       from_secret: dockerhub_username
#     password:
#       from_secret: dockerhub_password

# depends_on:
#   - amd64-mini-dockerhub
#   - arm64-mini-dockerhub

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: amd64-common-dockerhub

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: common.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-common-drone-amd64"

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: arm64-common-dockerhub

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: common.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-common-drone-arm64"

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# name: manifest-common
# steps:
# - name: manifest
#   image: plugins/manifest
#   settings:
#     spec: manifests/common-drone-manifest.tmpl
#     tag: "${DRONE_TAG}-common"
#     ignore_missing: true
#     username:
#       from_secret: dockerhub_username
#     password:
#       from_secret: dockerhub_password

# depends_on:
#   - amd64-common-dockerhub
#   - arm64-common-dockerhub

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: amd64-exec-env-dockerhub

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: exec-env.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-exec-env-drone-amd64"

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: arm64-exec-env-dockerhub

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: exec-env.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-exec-env-drone-arm64"

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# name: manifest-exec-env
# steps:
# - name: manifest
#   image: plugins/manifest
#   settings:
#     spec: manifests/exec-env-drone-manifest.tmpl
#     tag: "${DRONE_TAG}-exec-env"
#     ignore_missing: true
#     username:
#       from_secret: dockerhub_username
#     password:
#       from_secret: dockerhub_password

# depends_on:
#   - amd64-exec-env-dockerhub
#   - arm64-exec-env-dockerhub

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: amd64-torch-cpu-dockerhub

# platform:
#   arch: amd64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: torch-cpu.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-torch-cpu-drone-amd64"

# depends_on:
#   - manifest-common

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# type: docker
# name: arm64-torch-cpu-dockerhub

# platform:
#   arch: arm64

# steps:
#   - name: build and publish
#     image: plugins/docker
#     settings:
#       dockerfile: torch-cpu.Dockerfile
#       username:
#         from_secret: dockerhub_username
#       password:
#         from_secret: dockerhub_password
#       repo: "kernai/${DRONE_REPO_NAME}"
#       tag: "${DRONE_TAG}-torch-cpu-drone-arm64"

# depends_on:
#   - manifest-common

# trigger:
#   event:
#     - tag

# ---
# kind: pipeline
# name: manifest-torch-cpu
# steps:
# - name: manifest
#   image: plugins/manifest
#   settings:
#     spec: manifests/torch-cpu-drone-manifest.tmpl
#     tag: "${DRONE_TAG}-torch-cpu"
#     ignore_missing: true
#     username:
#       from_secret: dockerhub_username
#     password:
#       from_secret: dockerhub_password

# depends_on:
#   - amd64-torch-cpu-dockerhub
#   - arm64-torch-cpu-dockerhub

# trigger:
#   event:
#     - tag