#!/bin/bash

# version needs to be changed in build and push_to_dockerhub script and in the
# torch-cpu.Dockerfile
VERSION=v1.5.0

docker build -t kernai/refinery-parent-images:$VERSION-mini -f mini.Dockerfile .
docker build -t kernai/refinery-parent-images:$VERSION-common -f common.Dockerfile .
docker build -t kernai/refinery-parent-images:$VERSION-exec-env -f exec-env.Dockerfile .
docker build -t kernai/refinery-parent-images:$VERSION-torch-cpu -f torch-cpu.Dockerfile .
