#!/bin/bash

VERSION=v1.5.0
PLATFORMS=linux/amd64,linux/arm64

# both platforms: amd64 and arm64
docker buildx build -t kernai/refinery-parent-images:$VERSION-mini -f mini.Dockerfile --platform $PLATFORMS --push .
docker buildx build -t kernai/refinery-parent-images:$VERSION-common -f common.Dockerfile --platform $PLATFORMS --push .
docker buildx build -t kernai/refinery-parent-images:$VERSION-exec-env -f exec-env.Dockerfile --platform $PLATFORMS --push .
docker buildx build -t kernai/refinery-parent-images:$VERSION-torch-cpu -f torch-cpu.Dockerfile --platform $PLATFORMS --push .
